name: Build Halide amd64 deb package for debian unstable

on:
  push:
    branches: [ buildbot-debian ]

# DEB_BUILD_OPTIONS: nolto nopgo

jobs:
  linux:
    runs-on: ubuntu-latest
    container:
      image: debian:unstable-slim
      options: --privileged --cap-add=SYS_ADMIN --tmpfs /tmp:exec --tmpfs /__w/${{ github.event.repository.name }}/${{ github.event.repository.name }}:exec
    env:
      DIST: unstable
      DEBFULLNAME: Roman Lebedev
      DEBEMAIL: lebedev.ri@gmail.com
    steps:
      - name: Install necessary packages
        run: |
          set -xe
          tee /etc/dpkg/dpkg.cfg.d/force-unsafe-io > /dev/null <<EOT
          force-unsafe-io
          EOT
          tee /etc/apt/apt.conf.d/tmpfs > /dev/null <<EOT
          Dir::Cache::Archives "/tmp/apt/archives";
          APT::ExtractTemplates::TempDir "/tmp/apt/temp";
          EOT
          mkdir -p /tmp/apt/archives
          tee /etc/apt/apt.conf.d/80retry > /dev/null <<EOT
          Acquire::Retries "10";
          EOT
          tee /etc/apt/apt.conf.d/80recommends > /dev/null <<EOT
          APT::Install-Recommends "false";
          EOT
          tee /etc/apt/apt.conf.d/80suggests > /dev/null <<EOT
          APT::Install-Suggests "false";
          EOT
          tee /etc/apt/apt.conf.d/80forceyes > /dev/null <<EOT
          APT::Get::Assume-Yes "true";
          EOT
          tee /etc/apt/apt.conf.d/80fixmissing > /dev/null <<EOT
          APT::Get::Fix-Missing "true";
          EOT
          rm -rf /var/lib/apt/lists/*
          rm -rf /etc/apt/sources.list*
          tee /etc/apt/sources.list > /dev/null <<EOT
          deb http://debian-archive.trafficmanager.net/debian unstable main
          EOT
          apt-get update
          apt-get install debhelper \
                          debian-archive-keyring \
                          devscripts \
                          dh-python \
                          eatmydata \
                          fakeroot \
                          git \
                          git-buildpackage \
                          gpg-agent \
                          gpgconf \
                          pbuilder \
                          procps \
                          reprepro \
                          sudo \
                          \
                          xz-utils
          apt-get clean
      - name: Create baseline build environment
        run: |
          set -xe
          tee /etc/pbuilderrc > /dev/null <<EOT
          MIRRORSITE=http://debian-archive.trafficmanager.net/debian
          APTCACHE=/tmp/pbuilder/aptcache/
          BASETGZ=/tmp/pbuilder/base.tgz
          BUILDPLACE=/tmp/pbuilder/build/
          BUILDRESULT=/tmp/pbuilder/result/
          EATMYDATA=YES
          COMPRESSPROG=cat
          EXTRAPACKAGES="eatmydata"
          EOT
          tee /root/.gbp.conf > /dev/null <<EOT
          [DEFAULT]
          builder = /usr/bin/pdebuild
          EOT
          mkdir -p /tmp/pbuilder
          mkdir -p /tmp/pbuilder/aptcache
          mkdir -p /tmp/pbuilder/build
          mkdir -p /tmp/pbuilder/result
          eatmydata sudo pbuilder create
      - uses: actions/checkout@v3
        name: Fetch our git repository
        with:
          path: 'halide-src'
          fetch-depth: 0
      - name: Build the package
        run: |
          set -xe
          cd "$GITHUB_WORKSPACE/halide-src/"
          git checkout -B debian origin/debian
          sudo gbp buildpackage --git-dist=$DIST --git-verbose
          ls -lah "/tmp/pbuilder/result"
