name: Build Halide amd64 deb package for debian unstable

on:
  push:
    branches: [ buildbot-debian ]

jobs:
  linux:
    runs-on: ubuntu-latest
    env:
      BUILDER: pbuilder
      GIT_PBUILDER_OPTIONS: --mirror http://debian-archive.trafficmanager.net/debian --debootstrapopts "--variant=minbase" --debootstrapopts "--keyring=/usr/share/keyrings/debian-archive-keyring.gpg"
      GIT_PBUILDER_PDEBUILDOPTIONS: --buildresult /tmp/pbuilder/result
      DIST: unstable
      DEBFULLNAME: Roman Lebedev
      DEBEMAIL: lebedev.ri@gmail.com
      DEB_BUILD_OPTIONS: nolto nopgo
    steps:
      - name: Install necessary packages
        run: |
          set -xe
          sudo tee /etc/dpkg/dpkg.cfg.d/force-unsafe-io > /dev/null <<EOT
          force-unsafe-io
          EOT
          sudo tee /etc/apt/apt.conf.d/tmpfs > /dev/null <<EOT
          Dir::Cache::Archives "/tmp/apt/archives";
          APT::ExtractTemplates::TempDir "/tmp/apt/temp";
          EOT
          mkdir -p /tmp/apt/archives
          sudo tee /etc/apt/apt.conf.d/80retry > /dev/null <<EOT
          Acquire::Retries "10";
          EOT
          sudo tee /etc/apt/apt.conf.d/80recommends > /dev/null <<EOT
          APT::Install-Recommends "false";
          EOT
          sudo tee /etc/apt/apt.conf.d/80suggests > /dev/null <<EOT
          APT::Install-Suggests "false";
          EOT
          sudo tee /etc/apt/apt.conf.d/80forceyes > /dev/null <<EOT
          APT::Get::Assume-Yes "true";
          EOT
          sudo tee /etc/apt/apt.conf.d/80fixmissing > /dev/null <<EOT
          APT::Get::Fix-Missing "true";
          EOT
          sudo rm -rf /var/lib/apt/lists/*
          sudo apt-get update
          sudo apt-get install debhelper \
                               debian-archive-keyring \
                               devscripts \
                               dh-python \
                               eatmydata \
                               git \
                               git-buildpackage \
                               gpg-agent \
                               gpgconf \
                               pbuilder \
                               reprepro \
                               sudo \
                               xz-utils
          sudo apt-get clean
      - name: Create baseline build environment
        run: |
          set -xe
          sudo tee /etc/pbuilderrc > /dev/null <<EOT
          APTCACHE=/tmp/pbuilder/aptcache/
          BASETGZ=/tmp/pbuilder/base.tgz
          BUILDPLACE=/tmp/pbuilder/build/
          BUILDRESULT=/tmp/pbuilder/result/
          EATMYDATA=YES
          COMPRESSPROG=cat
          EXTRAPACKAGES="eatmydata"
          EOT
          mkdir -p /tmp/pbuilder/{aptcache,build,result}
          git-pbuilder create
      - uses: actions/checkout@v3
        name: Fetch our git repository
        with:
          path: 'halide-src'
          fetch-depth: 0
      - name: Build the package
        run: |
          set -xe
          cd "$GITHUB_WORKSPACE/halide-src/"
          git checkout -B debian origin/debian
          gbp buildpackage --git-pbuilder --git-dist=$DIST --git-verbose
          ls -lah "/tmp/pbuilder/result"
